export const appContent = {
  preview: {
    title: "Mobile preview",
    sizeLabel: "Frame 390 × 844 px",
  },
  login: {
    brand: "Wellnest",
    title: "บริการดูแลตัวเองถึงคอนโด",
    subtitle: "ล็อกอินเพื่อดูบริการ โปรโมชัน และเริ่มจองบริการส่วนตัว",
    loginLabel: "อีเมล หรือ เบอร์โทรศัพท์",
    loginPlaceholder: "plug@example.com หรือ 0812345678",
    passcodeLabel: "รหัสเข้าใช้งาน",
    passcodePlaceholder: "ใส่รหัสผ่านหรือ OTP",
    signInButton: "Sign in",
    createAccountButton: "Create account",
    socialDivider: "หรือเข้าสู่ระบบด้วย",
    note: "รอบ pilot ปุ่ม Apple ID, Facebook และ Gmail จะพาเข้าแอพเพื่อทดสอบ flow ก่อน ส่วน production จะต่อ OAuth/native provider จริง",
  },
  signup: {
    brand: "Wellnest",
    title: "สร้างบัญชี Wellnest",
    subtitle: "ใช้ข้อมูลนี้เพื่อจองบริการ แจ้งเตือน และดูแลความปลอดภัยระหว่างการให้บริการ",
    nameLabel: "ชื่อที่ใช้เรียก",
    namePlaceholder: "เช่น Plug",
    emailLabel: "อีเมล",
    emailPlaceholder: "plug@example.com",
    phoneLabel: "เบอร์โทรศัพท์",
    phonePlaceholder: "0812345678",
    passcodeLabel: "ตั้งรหัสเข้าใช้งาน",
    passcodePlaceholder: "อย่างน้อย 6 ตัว",
    createButton: "Create account",
    signInLink: "มีบัญชีแล้ว? Sign in",
    note: "ขั้นตอนจริงจะเพิ่มการยืนยัน OTP/Email และขอ consent ก่อนเปิดใช้งานจริง",
  },
  home: {
    greeting: "พร้อมดูแลพี่วันนี้",
    brand: "Wellnest",
    location: "Sathorn · Bangkok",
    heroLabel: "Private wellness",
    heroTitle: "จองบริการดูแลตัวเองแบบส่วนตัว",
    heroSubtitle: "เลือกบริการ เวลา และพื้นที่ให้ชัดเจน แล้วระบบจะจัดการขั้นตอนถัดไปอย่างเป็นระเบียบ",
    heroButton: "เริ่มจองบริการ",
    heroTrustTitle: "Verified care",
    heroTrustBody: "ยืนยันพื้นที่ก่อนจอง · ชำระเงินผ่านระบบ · ติดตามสถานะได้",
    servicesTitle: "เลือกบริการหลัก",
    viewAllButton: "ดูทั้งหมด",
    clinicsTitle: "Partner Clinics",
    clinicsAction: "จองกับคลินิก",
    awTitle: "AW",
    awEyebrow: "Featured campaign",
    awHeadline: "Wellness Week Privilege",
    awBody: "พื้นที่สำหรับ artwork โปรโมชันหลัก เช่น ส่วนลดสมาชิก แพ็กเกจช่วงเย็น หรือแบรนด์พาร์ทเนอร์",
    awButton: "ดูรายละเอียด",
  },
};

export const services = [
  { id: "massage", name: "นวดผ่อนคลาย", desc: "90 นาที · เหมาะหลังเลิกงาน", price: 1290, tag: "Popular" },
  { id: "aroma", name: "Aroma Recovery", desc: "120 นาที · ผ่อนคลายลึก", price: 1890, tag: "Premium" },
  { id: "product", name: "Wellness Kit", desc: "สินค้า wellness ส่งถึงคอนโด", price: 690, tag: "Product" },
  { id: "stretch", name: "Office Stretch", desc: "60 นาที · ลดออฟฟิศซินโดรม", price: 990, tag: "New" },
];

export const partnerClinics = [
  {
    id: "clinic-sathorn",
    name: "Sathorn Wellness Clinic",
    type: "Aroma recovery · Office stretch",
    area: "Sathorn · 1.8 km",
    address: "Empire Tower, Sathorn",
    headline: "Recovery หลังเลิกงานใกล้คอนโดและออฟฟิศ",
    promoTitle: "After-work recovery",
    promoBody: "รับส่วนลดเปิดตัวสำหรับรอบ 18:00-21:00 ในวันธรรมดา",
    note: "รับ booking หลังเลิกงาน",
    serviceId: "aroma",
    packages: [
      { serviceId: "aroma", name: "Aroma Recovery Session", price: 1890, duration: "120 นาที" },
      { serviceId: "massage", name: "Neck & Shoulder Recovery", price: 1290, duration: "90 นาที" },
    ],
  },
  {
    id: "clinic-langsuan",
    name: "Langsuan Recovery Studio",
    type: "Therapy room · Wellness kit",
    area: "Langsuan · 2.4 km",
    address: "Langsuan Village, Chidlom",
    headline: "Studio care สำหรับแพ็กเกจฟื้นฟู",
    promoTitle: "Studio care bundle",
    promoBody: "จอง service bundle พร้อม wellness kit ได้ในรอบเดียว",
    note: "เหมาะกับแพ็กเกจฟื้นฟู",
    serviceId: "stretch",
    packages: [
      { serviceId: "stretch", name: "Recovery Studio Session", price: 990, duration: "60 นาที" },
      { serviceId: "product", name: "Wellness Kit Consultation", price: 690, duration: "delivery" },
    ],
  },
];
